### ISSUE TITLE
Не полная каптча и не сменяет удочку

### ISSUE THREAD

**Issue by LilyaCharly** [Symb1OS/blackdesert-fishbot#10]
Не меняет удочку, и каптчу долго проверяет, иногда не вводит последнюю букву из каптчи, при условии что время еще есть. Просто не распознает ее.
![7](https://user-images.githubusercontent.com/39705572/49208910-c68a7300-f3c1-11e8-8d00-7cf2904a1398.png)
![8](https://user-images.githubusercontent.com/39705572/49208911-c68a7300-f3c1-11e8-8b31-9b0f64dd19bb.png)
![9](https://user-images.githubusercontent.com/39705572/49208912-c68a7300-f3c1-11e8-80c1-ca0646e9c160.png)
![10](https://user-images.githubusercontent.com/39705572/49208913-c7230980-f3c1-11e8-9bcd-3df3e53ba94c.png)

Установлена Java jdk1.8.0_191
Настройки как в описании бота
Версия бота 1.7.6

1) ошибка каптча, ее не полностью считывает бот
2) не сменяет удочки, в боте пишет Fishing detected и больше ничего не делает, только иногда бот повторно проводит єти же действия.

Скриншоты с logs, debug

**Comment by Symb1OS** [comment]
@LilyaCharly 

> 1. ошибка каптча, ее не полностью считывает бот

Бот иногда может допускать ошибки при длинных значениях. Капча распознается нейронной сетью (НН), которая обучена на выборке в 15 тысяч изображений, из них процент капч с длиной больше 5 символов очень невелик, соответственно НН недостаточно хорошо их распознает. Как только коллекция подрастет, я смогу ее улучшить.

> не сменяет удочки, в боте пишет Fishing detected и больше ничего не делает, только иногда бот повторно проводит єти же действия.

Откройте `resources/application.properties` и попробуйте заменить следующее свойство:

`bot.screen.space.offset.y=40` на `bot.screen.space.offset.y=20`

**Comment by LilyaCharly** [comment]
Спасибо, сейчас попробую, куплю самые дешевые удочки, проверю на них что бы время не терять.

Прикрепляю еще скриншоты на которых видно что удочка закончилась и вместо проверки удочки бот пишет Fishing detected.

**Comment by LilyaCharly** [comment]
![11](https://user-images.githubusercontent.com/39705572/49214108-91d0e880-f3ce-11e8-840a-0224c758bc6e.png)
![Uploading Снимок экрана (12).png…]()

**Comment by LilyaCharly** [comment]
Не помогло изменение. Прикладываю скриншот. Ожидал 14мин. 
![14](https://user-images.githubusercontent.com/39705572/49218559-64d60300-f3d9-11e8-84fc-03bd7ec2f00e.png)
![15](https://user-images.githubusercontent.com/39705572/49218560-64d60300-f3d9-11e8-9fc4-7ed01f84c253.png)

**Comment by Symb1OS** [comment]
Будет исправлено в новой версии

**Comment by Symb1OS** [comment]
Она еще не протестирована, но если хотите проверить работоспособность, можно скачать отсюда - [1.7.7](https://github.com/Symb1OS/blackdesert-fishbot/archive/master.zip)

**Comment by LilyaCharly** [comment]
Спасибо, сегодня протестирую и отпишусь про работу!

**Comment by LilyaCharly** [comment]
Возможно проблема с координатами инвентаря? Вот вроде открывает инвентарь с попыткой сменить удочки, но не получается и потом перезагружается и так по кругу каждые 3минуты. 
![17](https://user-images.githubusercontent.com/39705572/49233999-de80e780-f3ff-11e8-8816-f6db5c10c597.png)
![18](https://user-images.githubusercontent.com/39705572/49234000-de80e780-f3ff-11e8-963b-6d300771a8e5.png)

**Comment by LilyaCharly** [comment]
Вот еще скриншот
![16](https://user-images.githubusercontent.com/39705572/49234097-0ec88600-f400-11e8-85cb-e41d7b806bed.png)

**Comment by LilyaCharly** [comment]
В инвентаре нужно включать "Авто-сортировку"? Удочки в первой строчке выставляю. На компьютере жены и моем одинаковая проблема. Клиенты чистые, все по инструкции. Подскает отлично и капчу на ура читает. Вот только со сменой не понятно, как эти координаты подстроить? Может сбросить положения инвентаря, но не знаю как, уже перезапускал игру.

**Comment by ZlojMuzhik** [comment]
bot.rod.y | Координата верхнего-левого слота инвентаря по осе ординат. | 350
Поменяй на 356

**Comment by Symb1OS** [comment]
> В инвентаре нужно включать "Авто-сортировку"?

Нет, главное требование - они должны находиться в верхней строке инвентаря.

>  Вот только со сменой не понятно, как эти координаты подстроить? 

Координаты вы можете проверить самостоятельно.
Открыть `resources/application.properties`

Найти там следующие строки:
```
# Координата верхнего-левого слота инвентаря
bot.rod.x=1484 
bot.rod.y=350

# Смещение
bot.rod.dx=54
bot.rod.dy=0

```

Текущее положение курсора пишется в окне с ботом.

**Comment by LilyaCharly** [comment]
Не получилось, но вот кое-что заметил. В настройках все правильно указано и инвентарь правильно стоит. Но мышка почему-то показывает другие координаты в момент замены удочки из инвентаря.
![13](https://user-images.githubusercontent.com/39705572/49246731-4a724880-f41e-11e8-9ab7-b1c809825a5e.png)

Вот координаты мышки в момент замены удочки отличается от заданных по умолчанию координат. Хотя при этом правильно мышка собирает лут.

**Comment by LilyaCharly** [comment]
Они хаотично как то сбились и вот сейчас второй слот реликвию бот не взял, так как по другим координатам попытался подобрать.

**Comment by Symb1OS** [comment]
У меня сейчас тоже подобное случилось, помог сброс настроек до дефотных настроек.

![default](https://user-images.githubusercontent.com/6949746/49250484-f83a2300-f42f-11e8-8922-7bb9eccdf031.png)

**Comment by Symb1OS** [comment]
> Еще вопрос, у меня настройки стоят подымать только ивент + камни + ключи, в папках только те картинки что надо, но подымает бот и рыбу. Хотя отключены функции "рыба и неопознанное", Я так понимаю нужно с папки unsort, взять картинки не нужных рыб и скопировать в папку trash?

Да, все верно.

**Comment by Askandor** [comment]
> bot.rod.y
не помог данный вариант, бот так и не меняет удочки. Сделал полный сброс перед этим...
