### ISSUE TITLE
Парсинг капчи, поднятие лута.

### ISSUE THREAD

**Issue by MastaDan9** [Symb1OS/blackdesert-fishbot#11]
Столкнулся с новой проблемой.
1. Не парсит капчу, после того как введет капчу, стоит и ждет http://skrinshoter.ru/s/291118/WUVmrX4y
Check status parsing captcha
Status not identified. Go filter loot...
2. После того как переходит к фильтру лута, не может определить лут, зависает на этапе Check loot..

Версия 1.7.6 последняя. 
Java как и в гайде
Использую Arduino
Запускаю от Администратора
Перестал работать после ТЕХ работ.

Прикрепляю файлы лога.
[debug.log](https://github.com/Symb1OS/blackdesert-fishbot/files/2628509/debug.log)
[work.log](https://github.com/Symb1OS/blackdesert-fishbot/files/2628505/work.log)

**Comment by Symb1OS** [comment]
> Не парсит капчу, после того как введет капчу

Необходимы следующие скрины со статусом пасинга капчи:
- УСПЕХ;
- НЕУДАЧА.

> После того как переходит к фильтру лута, не может определить лут, зависает на этапе Check loot..

А в  `loot/unsort` при этом что ?

**Comment by MastaDan9** [comment]
> А в loot/unsort при этом что ?

Были скрины в unsort  , я перенес их от туда в отдельную папку. Все равно на луте останавливается

> Необходимы следующие скрины со статусом парсинга капчи:
Как отловить НЕУДАЧУ если всегда разгадывает правильно ?)

**Comment by Symb1OS** [comment]
Да просто ручками  неправильно ввести, необязательно чтобы бот работал при этом)

**Comment by MastaDan9** [comment]
УСПЕХ
http://skrinshoter.ru/s/291118/WBwwQDi0
НЕУДАЧУ 
http://skrinshoter.ru/s/291118/zAkuXS9q

**Comment by Symb1OS** [comment]
Мне не удается воспроизвести, по скринам бот работает штатно.

Попробуйте заново сбилдить, запустив в корне `build.bat`.

**Comment by MastaDan9** [comment]
Прикрепляю
[application.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/2629758/application.zip)

**Comment by Symb1OS** [comment]
Если еще не сделали ребилд, просьба заархивировать и приложить всю папку `target/blackdesert-fishbot`.

Попробую запустить, таким образом проверим в чем дело.

**Comment by MastaDan9** [comment]
Блин, я уже сделал ребилд и всё заработало), только не проверял еще смену удочек. 
А так всё работает и капчу быстро распознает

**Comment by Symb1OS** [comment]
Ок, тогда если повторится, проверим.
