### ISSUE TITLE
Куски (Offtopic)

### ISSUE THREAD

**Issue by SBleak** [Symb1OS/blackdesert-fishbot#12]
Сколько кусков выловить можно за ночь примерно?

**Comment by Symb1OS** [comment]
По разному бывает, зависит от уровня рыбалки, места, удачи и других факторов.

У меня на ГМ 20 в среднем около 20.

**Comment by zemidala** [comment]
у меня не эмулируется порт com2 , от чего это может быть?

**Comment by Symb1OS** [comment]
> у меня не эмулируется порт com2 , от чего это может быть?

Создать новую задачу и описать проблему подробно.
