### ISSUE TITLE
Долгая проверка улова

### ISSUE THREAD

**Issue by SBleak** [Symb1OS/blackdesert-fishbot#13]
Долгая проверка улова. После вылавливания рыбины, бот проверяет статус капчи и пишет, что не смог этого сделать или очень долго это делает. По сути он зависает тут минуты 2-3.  При повторном клёве, всё тоже самое ничего не меняется. 
PS После обновления и сброс интерфейса до дефолтного у меня проблема со сменой удочек пропала. Отличный бот для фарма кусов. Спасибо)

**Comment by Symb1OS** [comment]
> Долгая проверка улова. После вылавливания рыбины, бот проверяет статус капчи и пишет, что не смог этого сделать или очень долго это делает. По сути он зависает тут минуты 2-3. При повторном клёве, всё тоже самое ничего не меняется.

Просьба при повторном возникновении заархивировать с папку с ботом и скинуть мне.
