### ISSUE TITLE
Координаты удочек

### ISSUE THREAD

**Issue by OgerMW** [Symb1OS/blackdesert-fishbot#18]
Доброго времени суток. После совета сбросить все настройки по умолчанию, дабы сломанная удочка стала меняться на целую, я так и поступил, но не помогло. Я так понимаю, бот не находит удочки по заданным координатам. Где в настройках бота хранятся эти значения (цифры с координатами)? Попробую поиграться с ними, может поможет.

**Comment by LilyaCharly** [comment]
У меня проблема немного другого рода. Бот не видит первый слот, и последние 2. Хотя координаты верно и инвентарь верно установлены. Такое даже после сброса настроек и интерфейса. Ребилд не помог. И иногда среди лута не может собрать вторую ячейку, мышка переходит не на такие координаты как указаны в боте.

**Comment by OgerMW** [comment]
Я правильно понял, в application.properties строчки **bot.rod.y=350** и **bot.rod.x=1484** - это местоположение удочки в первом слоте, а строчки **bot.rod.dy=0** и **bot.rod.dx=54** - это насколько пикселей нужно сместиться курсора, к каждой последующей удочке?

**Comment by LilyaCharly** [comment]
Да все правильно, в открытом боте видно координаты когда наводите курсором на инвентарь.

**Comment by OgerMW** [comment]
Самое забавное, что данные координаты идеально совпадают с моими, но удочка не меняется =(

**Comment by OgerMW** [comment]
Update. Помогла полная переустановка бота. Хз почему.
