### ISSUE TITLE
Работа на слабом ПК

### ISSUE THREAD

**Issue by vesprin** [Symb1OS/blackdesert-fishbot#19]
Привет.

Бот версии 1.7.7, режим работы ROBOT.
Захотел поставить на рабочем ноуте. Конфиг i5 7th gen, 16gb, видеокарты нет (встройка UHD). Посему на оверминималках в игре 14-16 фпс в любом случае.
Из-за этого все действия происходят с задержкой в несколько миллисекунд.
Столкнулся с проблемами:

1. Подсечка рыбы происходит не вовремя. Пробел нажимается, но само действие в игре происходит с задержкой. И получается что ползунок в большинстве случаев уже в красной зоне.
Пытался подстроить играясь цифрой в строчке "bot.delay.cutfish.before". Но так и не получил результата. Может я не то делал? Буду крайне благодарен если поможете.

2. 3-4 раза из 30 попыток ползунок всё-таки попал в синюю зону. Но на этапе капчи бот все разы зафейлился на 1й букве. 
Как пример капча "w-s-a-a-d", а бот видел всего пару букв типа "a-d". Фейлился, после чего зависал на этапе чека статуса капчи.
Пытался менять значения в строках bot.kapcha.noise.iteration и bot.keyboard.input.delay, но опять без результата.
Пару раз пересобирал бота, тоже не помогло.

Может всё-таки как-то можно "подогнать" бота под ноут с таким фпс? :)
Папки log и resources в аттаче, вдруг помогут.
Заранее спасибо.
[log and resources.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/2649617/log.and.resources.zip)

UPD. На игровом компе запустил - всё работает как часы.

**Comment by Symb1OS** [comment]
Привет,

1. `bot.delay.cutfish.before` тут не поможет, потому как задержка будет вызываться каждую итерацию, что скорее усугубит ситуацию. Тут единственный варинт без попытки оптимизации бота под непроизводительные машины изменить параметр `bot.screen.subline`, уменьшив размер, к примеру так: `997, 412, 3, 4`  и заменить шаблон `resources/templates/LINE` [NEW_LINE.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/2652411/NEW_LINE.zip), чтобы он совпадал по размеру. Плюс можно удалить `resources/templates/space/SPACE_EU`, чтобы парсер не тратил время на сравнение еще и с этим шаблоном, который нужен только для евро сервера;
2. Да, для небольшого ускорения очистки от шума можно уменьшить значение `bot.kapcha.noise.iteration` где-нибудь до 30, но ниже уже лучше не опускать, он будет работать быстрее, но качество распознавания снизится. После того как подберете значение с которым бот будет возвращать корректный результат вовремя (чтобы оставалось хоть немного времени на ввод капчи). После этого можно уменьшить задержку на скорость ввода `bot.keyboard.input.delay` в зависимости от оставшегося времени. Но ниже `50` не советую.

**Comment by vesprin** [comment]
Спасибо, попробую

**Comment by vesprin** [comment]
Не сильно разбираюсь в теме, по этому вставил просто предложенные цифры и заменил LINE.
> 1. изменить параметр `bot.screen.subline`, уменьшив размер, к примеру так: `997, 412, 3, 4`  и заменить шаблон `resources/templates/LINE` [NEW_LINE.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/2652411/NEW_LINE.zip)

Увы, всё-равно не попадает. Всегда тыкается в красной зоне.
![fail](https://user-images.githubusercontent.com/45634129/49580275-3915c880-f957-11e8-8ce4-b2f3e0ec38c4.jpg)

Мне кажется ноутбучный i5 7-го поколения должен справляться с задачей. Проблема именно в том что видеокарты нет и из-за низкого фпс действия происходят с задержкой, нет?

В какую сторону надо поиграться цифрами в `bot.screen.subline` чтоб настроить? Возможно ли это?

**Comment by Symb1OS** [comment]
Данная стадия очень чувствительна к фпс, потому как полоска находится в синей зоне очень непродолжительное время. В вашем случае получается то что он слишком поздно узнает(из-за загруженности процессора), что полоска находится синей зоне и соответственно не успевает в нее попасть.

> В какую сторону надо поиграться цифрами в bot.screen.subline чтоб настроить? Возможно ли это?

Ну если предыдущая оптимизация не помогла, тогда тут особо ничего не сделаешь, разве что поиграться с настройками в самой игре, чтобы хоть как-то повысить производительность. Или дорабатывать бота для подобных случаев.

**Comment by vesprin** [comment]
Окей, я вместо очень низких настроек только что включил "режим оптимизации" и вместо 17 фпс получил 40-50. Даже не подозревал что в бдо может быть на столько херовый графон :)
Теперь бот на дефолтных настройках хорошо подсекает рыбу и вводит капчу.
Спасибо за помощь :)
