### ISSUE TITLE
Нераспознанное фильтр лута по папкам

### ISSUE THREAD

**Issue by MastaDan9** [Symb1OS/blackdesert-fishbot#20]
Добрый день.
Хочу рассортировать папку "unknown"
Нужно ли переименовывать картинки ?

**Comment by OgerMW** [comment]
Нет

**Comment by Askandor** [comment]
Вопрос не по теме....
У всех после вчерашнего патча слетели споты в реках? 
Еще во вторник ловил 23-30 кусков за ночь и 40-50 голдовой рыбы. Сегодня утром 6 кусков и 3 золота...

**Comment by OgerMW** [comment]
> Вопрос не по теме....
> У всех после вчерашнего патча слетели споты в реках?
> Еще во вторник ловил 23-30 кусков за ночь и 40-50 голдовой рыбы. Сегодня утром 6 кусков и 3 золота...

Не исключено, я Лаврака для квеста 3е сутки не могу поймать. Тупо 60+ часов и 0 Лавраков.
