### ISSUE TITLE
В большинстве случаев неверно распознает капчу

### ISSUE THREAD

**Issue by vesprin** [Symb1OS/blackdesert-fishbot#21]
Привет. 

Режим работы ROBOT, последняя версия бота.
Поставил настройки графики на низко, выкрутил яркость на -50, контрастность на +50 (всё как на видео)
Но всё-таки в большинстве случаев бот неверно распознает капчу.
Наблюдал, безошибочные срабатывания были только для капч из 2х символов.
Большинство капч всё-таки состояли из 4-5 символов.
Правильно были распознаны только около 30% (ориентировочно).
При чем бот вместо 4-5 букв часто видел 6-8 букв. Забавно, что они были какие-то рандомные и даже первая буква чаще всего была не верна.

Попробовал увеличить значение в bot.kapcha.noise.iteration до 58 (вроде же качество распознавания должно быть лучше).
Но не помогло.

Что можно сделать чтоб поднять качество распознавания? (комп мощный, может нагрузить побольше чтоб НН четче работал?)

Вот мои логи и настройки.
[logs and resources.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/2652482/logs.and.resources.zip)

Заранее спасибо за помощь.

**Comment by Symb1OS** [comment]
Привет,

> Попробовал увеличить значение в bot.kapcha.noise.iteration до 58 (вроде же качество распознавания должно быть лучше).
Но не помогло.

`bot.kapcha.noise.iteration` влияет только на очистку капчи от шума, выше `50` ставить нет никакого смысла. 

> Что можно сделать чтоб поднять качество распознавания? (комп мощный, может нагрузить побольше чтоб НН четче работал?)

Капча очищается от шума на вашем ПК, после этого отправляется на мой сервер, парсится, после чего возвращает результат. 

---

Вообще на капчах длиной до 8 символов он должен успешно отрабатывать в 99% случаях. Скорее всего что-то с настройками не так у вас.

Попробуйте в `application.properties` найти следующее свойство `bot.screen.debug.captcha` и установить в `true`. После этого дать поработать пару часиков, чтобы накопилось изображений. Сохранятся они будут в `resoures/debug/captcha` и скинуть их мне сюда.

**Comment by vesprin** [comment]
Окей, спс, на ночь поставлю. Завтра всё скину

**Comment by vesprin** [comment]
Пожалуйста.
В аттаче сами скрины капчи, скрины успеха/провала, так-же лог
[captchdata.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/2655327/captchdata.zip)

**Comment by Symb1OS** [comment]
> А вот саму капчу разгадывает почти всегда неверно :(

Так это понятно, они у вас вообще не очищены от шума. 

Какие у вас:
![20181207_022433_811](https://user-images.githubusercontent.com/6949746/49635825-f9f87d80-fa11-11e8-885d-2386bab4b107.jpg)

Должно быть:
![image](https://user-images.githubusercontent.com/6949746/49635635-7ccd0880-fa11-11e8-8f41-8a3b34709ce4.png)

Удалите `resources/application.properties`, а лучше вообще удалите папку с ботом и скачайте, установите по новой.

**Comment by vesprin** [comment]
хорошо, сделаю, напишу.
Какая ещё может быть причина того что оно не чистит от шума? Если вдруг не сработает, то какой ещё есть способ поправить?

**Comment by Symb1OS** [comment]
Единственная причина может крыться в этом параметре `bot.kapcha.noise.iteration=50(по умолчанию)`. Судя по логу очистка выполняется мгновенно, хотя должна работать не меньше секунды даже не очень мощных процессорах.

```
[07.12.2018 02:15:22] - Parsing captcha...
[07.12.2018 02:15:22] - Cleaning captcha...
[07.12.2018 02:15:22] - Cleaning ended...
```

Причем в смежной теме у вас подобных проблем не возникает, там капчи как надо выглядят.

---

И еще если что-то меняете активно в настройках, а потом неуверены в том что там понаделали, лучше удалить их, и перезапустить бот чтобы он он восстановил дефолтные настройки. 

Если бот не работает на дефолтных настройках, значит вы что-то делаете не так, либо у вас проблемы с настройками в игре\системе.

**Comment by vesprin** [comment]
Спасибо, помогла полная переустановка jdk и бота с перезагрузками
