### ISSUE TITLE
Не правильно мышка клацает поднять второй лут

### ISSUE THREAD

**Issue by LilyaCharly** [Symb1OS/blackdesert-fishbot#23]
Отчёты о багах должны содержать:
- Версию приложения.   1.7.7
- Режим работы `ROBOT` 
-  Не собирает второй лут
- Переустановил бота + полный сброс настроек
- Содержимое `resources/application.properties` по умолчанию
- По мере возможности, прикрепите визуальное подтверждение бага. Скриншоты, видео и/или анимационные гифы. не удалось успеть сделать скриншот

Возможно причина ноутбук с тачпадом? Может ему нужна проводная мышка? Удочки меняет, все успешно, кроме вторых итемов в луте. Координаты установлены верно, мышку не туда отводит.

**Comment by Symb1OS** [comment]
**_Symb1OS commented 2 days ago_**

Стоит проверить масштаб в игре\windows\настройках видеокарты везде должно быть 100%.

---

**_LilyaCharly commented 2 days ago_**

Вопрос как проверить масштаб в windows и на видеокарте? Ноутбук с экраном IPS FullHD, и видеокарта Nvidia 1050 Ti, Windows 10. Помогите пожалуйста найти где смотреть. У жены на ПК идеально уже работает последняя 1.7.7 и замена удочки и второй и третий лут собирает. А у меня на ноутбуке почему-то не хочет, хотя без спец настроек, чистая виндовс и все гладко настроено по инструкции без изменений.

---

**_Symb1OS commented 2 days ago_**

Ну погуглить.
Вот как пример - https://faqpc.ru/kak-umenshit-masshtab-ekrana/

---

_**LilyaCharly commented 11 hours ago**_

Исправил в windows 10 масштаб на 100%, был 125%. В видеокарте nvidia geforce не нашел этих параметров, и в игре стоит по умолчанию 100 масштаб. Второй и третий лут собирает уже! Вопрос со сменой удочкой пока не понятен, при установке таймера в смену удочки 5000ms удочку не меняет, может из за того что рыбалка активна в тот момент.

---

**Comment by LilyaCharly** [comment]
https://youtu.be/A5DjYXce4y8 вот масштаб везде 100%, настройки сбросил, бот чистый и java последняя на чистой виндовс без настроек

**Comment by LilyaCharly** [comment]
первый слот не меняет и потом так же проблема с другими, бот через раз работает корректно со сменой удочек и со вторым лутом

**Comment by Symb1OS** [comment]
Просьба [скачать тестовую версию](https://github.com/Symb1OS/blackdesert-fishbot/archive/master.zip), после запуска в интерфейсе нажать кнопку `Тест`. Бот начнет последовательно менять удочки 1-8.  Прогнать тест 2 раза.

Желательно снять видео и приложить work.log сюда.

**Comment by LilyaCharly** [comment]
https://www.youtube.com/watch?v=qdMhi2CpvQA&feature=youtu.be


[work.log](https://github.com/Symb1OS/blackdesert-fishbot/files/2664005/work.log)

**Comment by Symb1OS** [comment]
[Обновил тестовую версию](https://github.com/Symb1OS/blackdesert-fishbot/archive/master.zip).

Попробуйте опять использоваться `Тест`.

**Comment by LilyaCharly** [comment]
Завтра утром скину отчет как попробую, не было пару дней возле пк.
