### ISSUE TITLE
Произошла ошибка при загрузке скетча

### ISSUE THREAD

**Issue by Gordein** [Symb1OS/blackdesert-fishbot#24]
Произошла ошибка при загрузке скетча,че делать?

**Comment by Symb1OS** [comment]
> Задачи, которые не содержат в себе никакой информации для анализа игнорируются.

**Comment by Gordein** [comment]
Понимаю, почему у вас загружается, а у меня нет,если делаю все по гайду

сб, 8 дек. 2018 г., 1:00 ПП Symb1OS notifications@github.com:

**Comment by Symb1OS** [comment]
Если хотите чтобы вам помогли как минимум надо предоставить следующую информацию:
- какая у вас плата arduino;
- скриншот ошибки.

Так же для начала следует прочитать [вики](https://github.com/Symb1OS/blackdesert-fishbot/wiki)
