### ISSUE TITLE
Бот меняет удочку только 2 раза

### ISSUE THREAD

**Issue by Askandor** [Symb1OS/blackdesert-fishbot#25]
Странные дела вообщем то. В настройках бота стоит что у меня 7 удочек для замены. 
Как только начинается процесс замены вот что происходит:
1. 
Бот начинает чекать слоты 1-8 для замены. 
Available: 7/8
[08.12.2018 03:58:34] - Parsing command: Rod[1480,365]
[08.12.2018 03:58:52] - Thread stop.
[08.12.2018 03:58:52] - Need Restart. Restarted after 10 second...
[08.12.2018 03:59:02] - Start...
удочка чекается, но бот не берет ее в руки
стоит 10 минут на период активности смены удочки
2. 
[08.12.2018 04:09:16] - Available: 6/8
удочка чекается, но бот не берет ее в руки
3.
 Waiting time for fish is out..
[08.12.2018 04:19:58] - Start change rod...
[08.12.2018 04:19:58] - Checking availability fishing rod..
[08.12.2018 04:19:58] - New fishing rod found. Use..
[08.12.2018 04:19:58] - Available: 5/8
[08.12.2018 04:19:58] - Parsing command: Rod[1588,365]
[08.12.2018 04:20:16] - Thread stop.
[08.12.2018 04:20:16] - Need Restart. Restarted after 10 second...
удачная попытка, бот берет удочку
4. 
Происходит стандартная ловля, бот работает в штатном режиме
5. 
У удочки закончилась прочность
[08.12.2018 06:05:11] - Available: 4/8
[08.12.2018 06:05:11] - Parsing command: Rod[1642,365]
6. 
Удочку опять не удается поменять, повторяется цикл 
7. 
[08.12.2018 06:26:35] - New fishing rod found. Use..
[08.12.2018 06:26:35] - Available: 2/8
[08.12.2018 06:26:35] - Parsing command: Rod[1750,365]
Удача, эту удочку бот берет
8. 
Удочка меняется, бот работает...
9. 
[08.12.2018 08:05:10] - Available: 1/8
[08.12.2018 08:05:10] - Parsing command: Rod[1804,365]
[08.12.2018 08:05:27] - Thread stop.
10. 
Бот снова не может взять удочку.
![default](https://user-images.githubusercontent.com/45481333/49685104-795b7f00-faee-11e8-8f26-ca12c938c91a.png)
на скриншоте показаны слоты, в которых лежат удочки.
красный слот- место где произошла удачная замена.
Что делать, как фиксить?

**Comment by Askandor** [comment]
В окне debug
1. 
[08.12.2018 03:58:34] - Empty command
[08.12.2018 03:58:34] - x: 1480; y: 365
[08.12.2018 03:59:18] - Empty command
2. 
[08.12.2018 04:09:16] - Empty command
[08.12.2018 04:09:16] - x: 1534; y: 365
[08.12.2018 04:10:00] - Empty command
3.
[08.12.2018 04:19:58] - Empty command
[08.12.2018 04:19:58] - x: 1588; y: 365
[08.12.2018 04:20:42] - Empty command
4. 
[08.12.2018 06:05:11] - Empty command
[08.12.2018 06:05:11] - x: 1642; y: 365
[08.12.2018 06:05:55] - Empty command
5. 
[08.12.2018 06:15:53] - Empty command
[08.12.2018 06:15:53] - x: 1696; y: 365
[08.12.2018 06:16:37] - Empty command
6. 
[08.12.2018 06:26:35] - Empty command
[08.12.2018 06:26:35] - x: 1750; y: 365
[08.12.2018 06:27:19] - Empty command
7. 
[08.12.2018 08:05:10] - Empty command
[08.12.2018 08:05:10] - x: 1804; y: 365
[08.12.2018 08:05:53] - Empty command
каждая координата совпадает с ячейкой инвентаря в которой лежит удочка

**Comment by Symb1OS** [comment]
Хорошо бы заснять момент на видео, когда не удается сменить удочку, чтобы я мог примерно прикинуть в чем проблема.

**Comment by Askandor** [comment]
> Хорошо бы заснять момент на видео, когда не удается сменить удочку, чтобы я мог примерно прикинуть в чем проблема.

ок - сегодня сделаю

**Comment by Askandor** [comment]
> Хорошо бы заснять момент на видео, когда не удается сменить удочку, чтобы я мог примерно прикинуть в чем проблема.

https://youtu.be/w9Fe7KzDmXg

**Comment by LilyaCharly** [comment]
А если лут вторую ячейку не подымает? Может из-за ноутбука или беспроводной мышки? Уже устал переустанавливаиь бота и сбрасывать настройки. Может тоже на видео записать как курсор не правильно двигается по другим коррдинатам?

**Comment by Symb1OS** [comment]
Ну так а по масштабу что? Переустановка временно решает проблему?

Не знаю насчет ноута, не приходилось тестить на них, больше похоже на проблему с масштабом.

**Comment by Askandor** [comment]
> Ну так а по масштабу что? Переустановка временно решает проблему?
Вечером проверю, в настройках видео было включено вертуальное сверхвысокое разрешение. Но везде стояло 1920/1080 так что наврятли это та проблема. Переустановка бота проблему не решала, наблюдалась она еще с предыдущей версии.

**Comment by LilyaCharly** [comment]
Вопрос как проверить масштаб в windows и на видеокарте? Ноутбук с экраном IPS FullHD, и видеокарта Nvidia 1050 Ti, Windows 10. Помогите пожалуйста найти где смотреть. У жены на ПК идеально уже работает последняя 1.7.7 и замена удочки и второй и третий лут собирает. А у меня на ноутбуке почему-то не хочет, хотя без спец настроек, чистая виндовс и все гладко настроено по инструкции без изменений.

**Comment by Symb1OS** [comment]
Ну погуглить.
Вот как пример - https://faqpc.ru/kak-umenshit-masshtab-ekrana/

**Comment by Askandor** [comment]
> Ну так а по масштабу что? Переустановка временно решает проблему?
Вообщем проблему решил таким странным способом - как только бот делает заброс, ставлю курсор мышки на первую удочку как можно ближе к краю инвентаря - этого хватает что бы бот 2 раза успешно сменил ее, а потом координаты слетают все равно.
Проверил - везде стоит 100% масштаб, интерфейс сбрасывал, у бота скачал новую версию и удалил перед этим файл настроек. Хрен его знает как это происходит...

**Comment by Symb1OS** [comment]
А вы запускаете тоже на ноутбуке?

**Comment by Askandor** [comment]
> А вы запускаете тоже на ноутбуке?

Нет, на станционарном пк с хорошим железом.

**Comment by Askandor** [comment]
upd. Все хуже)
Если при ловле рыбы 2 итема в луте, (треш+нужный) бот пытается их поднять, сбивая тем самым положение мышки. В итоге нужный лут не поднимается, и смена удочек потом перестает работать. Как фиксить эти координаты?

**Comment by Symb1OS** [comment]
А при смене первой удочки он всегда перемещает курсор на разные координаты или на одни и те же?

**Comment by Askandor** [comment]
> А при смене первой удочки он всегда перемещает курсор на разные координаты или на одни и те же?

на разные, причем если я НЕ поставлю курсор на удочку в 1й ячейке инвентаря (в определенную область, он потом не сможет ее взять, а возьмет 2-7). 
Когда происходит попытка поднять 2ю ячейку лута (в 1й мусор) он опять же спотыкается на координатах, не выполняет подъем (реликвии или ивент итема) и соответственно на удочках так же спотыкается и замена рандомной 2-7.

**Comment by LilyaCharly** [comment]
Исправил в windows 10 масштаб на 100%, был 125%. В видеокарте nvidia geforce не нашел этих параметров, и в игре стоит по умолчанию 100 масштаб. Второй и третий лут собирает уже! Вопрос со сменой удочкой пока не понятен, при установке таймера в смену удочки 5000ms удочку не меняет, может из за того что рыбалка активна в тот момент.

**Comment by Askandor** [comment]
> А при смене первой удочки он всегда перемещает курсор на разные координаты или на одни и те же?

Вот видео (с комментариями внутри)
https://www.youtube.com/watch?v=Pu3JfgktEE8&feature=youtu.be

**Comment by Askandor** [comment]
> Не показали настройки игры с масштабом.
> 
> Попробуйте перед каждой сменой удочки устанавливать мышку по координатам `x=0, y=0`. И сделать 2 круга смены удочек по 8 штук, чтобы можно было увидеть зависимость.
> 
> Попробуйте так же переустановить JDK.

оба варианта не помогли,на неделе попробую полностью снести систему и почищу диски. отпишусь тогда о результате на чистой системе.

**Comment by charon166** [comment]
![image](https://user-images.githubusercontent.com/45757517/49869194-bd1cf400-fe20-11e8-9fda-724c9932e584.png)
У меня странно меняет удочки, хотя в Тесте все нормально.

**Comment by Symb1OS** [comment]
@Askandor 

Просьба проверить, возникает ли проблема в последней версии?
