### ISSUE TITLE
Не работает обнаружение Space

### ISSUE THREAD

**Issue by TrurlMcByte** [Symb1OS/blackdesert-fishbot#26]
версия 1.7.9
комп очень мощный, все сделано по вики
```
bot.input.mode=ROBOT
bot.language=\u0420\u0443\u0441\u0441\u043A\u0438\u0439
```

заклинивает на ```Wait fish..```
Если вернуть яркость и покрутить "головой", то иногда срабатывает ```Parsing command: space``` (чаще ложно, но тут и так ясно) и вот после этого все остальное отрабатывает гарантировано (в том числе распознавалка капчи, не взирая на настройки яркости)

в отладке waitfish при ```bot.screen.debug.waitfish=true``` что-то вроде: 
![20181212_070254_243](https://user-images.githubusercontent.com/2944622/49848330-51656780-fddd-11e8-9c25-933d29bd7418.jpg)
![20181212_070254_260](https://user-images.githubusercontent.com/2944622/49848331-51656780-fddd-11e8-9c6c-961ef1c4a27e.jpg)
![20181212_070254_276](https://user-images.githubusercontent.com/2944622/49848332-51656780-fddd-11e8-8d64-03b53ae99f68.jpg)
![20181212_070254_293](https://user-images.githubusercontent.com/2944622/49848333-51656780-fddd-11e8-881a-6eefdcdaec63.jpg)
![20181212_070254_310](https://user-images.githubusercontent.com/2944622/49848334-51fdfe00-fddd-11e8-8ad8-979b45f6ad96.jpg)

**Comment by Symb1OS** [comment]
Просьба приложить эти же скрины, только запуская с манимальной яркостью.

**Comment by shynobi13** [comment]
Проблема полностью  така я же кака и  у меня

**Comment by TrurlMcByte** [comment]
master (1.8.0) не глючит в тех же условиях

**Comment by shynobi13** [comment]
> master (1.8.0) не глючит в тех же условиях

Подскажите где скачать 1.8.0?

**Comment by shynobi13** [comment]
Уже установил 1.8, проблема осталась, (на ноутбуке). Поставили 1.7.9 на ПК для теста там все работает з прекрасно. Не знаю где искать проблему

**Comment by Symb1OS** [comment]
> > master (1.8.0) не глючит в тех же условиях
> 
> Подскажите где скачать 1.8.0?

[Тестовая версия](https://github.com/Symb1OS/blackdesert-fishbot/archive/master.zip).

Но надо учитывать то, что она она не всегда может работать корректно, так как постоянно изменяется.

> Уже установил 1.8, проблема осталась, (на ноутбуке).

Проблема скорее всего с разрешением, либо масштабом в `windows\настройках видеокарты\игре`.
