### ISSUE TITLE
Не собирает голдовую рыбу ( Судак и Восточный окунь )

### ISSUE THREAD

**Issue by pirogx** [Symb1OS/blackdesert-fishbot#27]
Компьютер хороший , не  собирает голдовую рыбу а именно 2 рыбины ( Судак и Восточный окунь ) - обе рыбы есть в папке loot>ok>fish , также проверил папку loot>trash - там этих рыбин нет . За ночь не выловил ни одну из этих рыб , утром переустановил  бота и с 5 до 9 утра он их не выловил .

**Comment by Symb1OS** [comment]
Просьба приложить сюда иконки.

**Comment by Symb1OS** [comment]
А лучше даже заархивировать папку `resources/loot` и приложить сюда.

**Comment by pirogx** [comment]
[loot.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/2673392/loot.zip)

**Comment by charon166** [comment]
> [loot.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/2673392/loot.zip)

путь папки точно такой? ***\target\blackdesert-fishbot_1.8.0\resources\loot***

**Comment by pirogx** [comment]
C:\blackdesert-fishbot-1.7.9\target\blackdesert-fishbot_1.7.9\resources\loot
полный путь
