### ISSUE TITLE
  Новые ивентовые печати

### ISSUE THREAD

**Issue by charon166** [Symb1OS/blackdesert-fishbot#28]
Добавили новые печати
![20181213_001532_676](https://user-images.githubusercontent.com/45757517/49900876-e49bad00-fe70-11e8-8b5f-faf401e092ff.jpg)
![20181213_002525_119](https://user-images.githubusercontent.com/45757517/49900881-e5ccda00-fe70-11e8-91b9-697dd7c85d51.jpg)

Бывает что при ловле за раз ловиться рыба и Печать охотника 2шт. Скрипт наводиться на печать и жмет ПКМ, а так как их 2шт открывается меню: 
![image](https://user-images.githubusercontent.com/45757517/49901070-507e1580-fe71-11e8-8fac-b62c3a4f782c.png)
 И подобрать он уже их не может.
 Нужно бы поправить.

**Comment by en3my666** [comment]
Временно решил проблему закидыванием 2шт в мусор (не такой уж и ценный дроп)

**Comment by pirogx** [comment]
ценный , за ночь насобирал 100шт( это только бот собирал по 1) а они а основном по 2 идут .

**Comment by Symb1OS** [comment]
Исправил в [тестовой версии](https://github.com/Symb1OS/blackdesert-fishbot/archive/master.zip).

**Comment by Symb1OS** [comment]
Исправлено в [новой версии](https://github.com/Symb1OS/blackdesert-fishbot/releases/tag/1.8.0).
