### ISSUE TITLE
ето нормалъно?

### ISSUE THREAD

**Issue by matreh** [Symb1OS/blackdesert-fishbot#3]
исполъзывал "install" выкинуло в начяле сразу ошыбку

Install pip dependency? (y/n) y
Install dependency
torch-0.4.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.
Collecting torchvision
  Using cached https://files.pythonhosted.org/packages/ca/0d/f00b2885711e08bd71242ebe7b96561e6f6d01fdb4b9dcf4d37e2e13c5e1/torchvision-0.2.1-py2.py3-none-any.whl
Collecting torch (from torchvision)
  Using cached https://files.pythonhosted.org/packages/5f/e9/bac4204fe9cb1a002ec6140b47f51affda1655379fe302a1caef421f9846/torch-0.1.2.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ХХХ\AppData\Local\Temp\pip-install-_3zsbu0w\torch\setup.py", line 11, in <module>
        raise RuntimeError(README)
    RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

    Please follow the instructions at http://pytorch.org/ to install with miniconda instead.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ХХХ\AppData\Local\Temp\pip-install-_3zsbu0w\torch\

**Comment by Symb1OS** [comment]
Можно попробовать установить вручную [отсюда](https://pytorch.org/)
