### ISSUE TITLE
Календарь

### ISSUE THREAD

**Issue by ye6jlko** [Symb1OS/blackdesert-fishbot#32]
Отчёты о багах должны содержать:
Версия 1.8.1
Производительность высокая
Режим работы "ROBOT"
Через определенное время работы от 20 минут до 120 минут, бот либо произвольно стопается, либо перестает работать после ~3 минут ожидания рыбы. Удочка целая, задача на смену удочки не активирована, но висел не закрытый "ESC" после скипа календаря
"[14.12.2018 13:35:23] - Waiting time for fish is out..
[14.12.2018 13:35:23] - Start change rod...
[14.12.2018 13:35:23] - Checking availability fishing rod..
[14.12.2018 13:35:23] - Free fishing rods are locked. Finish work.
[14.12.2018 13:35:23] - Send telegram notification.
[14.12.2018 13:35:38] - Thread stop."
По-большей мере, хотелось бы узнать, можно ли отключить скипанье календаря после каждой рыбы? Не афкшу сутками и ставлю бота как правило уже после получения календаря
Извиняюсь за кривой запрос, пишу первый раз и трудновато сформулировать грамотно проблему.

**Comment by ye6jlko** [comment]
@Symb1OS благодарю)

**Comment by ye6jlko** [comment]
А еще такой вопрос. Можно ли пофиксить ложные срабатывания на чат? В той области никакой информации нет, а бот пишет что было получено сообщение
[Скрин](https://yadi.sk/i/L0EOd_62arwdVQ)

**Comment by LilyaCharly** [comment]
По поводу чата, я его просто в интерфейсе отключаю на время работы бота. Это быстро и удобно.

**Comment by Symb1OS** [comment]
> По-большей мере, хотелось бы узнать, можно ли отключить скипанье календаря после каждой рыбы? 

В [новой версии](https://github.com/Symb1OS/blackdesert-fishbot/releases/tag/1.8.2) скип календаря отключен по умолчанию. В настройки добавлено свойство `bot.state.skip_calendar=false`.

> А еще такой вопрос. Можно ли пофиксить ложные срабатывания на чат? В той области никакой информации нет, а бот пишет что было получено сообщение

Попробуйте включить режим отладки для ПМ. Для этого в `resources/applicatiion.properties` установите свойство `bot.screen.debug.pmmessage=true`. Вся отладочная информация попадет в `debug`. Как вновь ошибочно отправиться оповещение просьба скинуть содержимое этой папки сюда.

**Comment by zemidala** [comment]
> По поводу чата, я его просто в интерфейсе отключаю на время работы бота. Это быстро и удобно.

а где чат отключается, а то у меня бот сам его нажимает и после этого бот подвисает, вернее ничего не делает.
