### ISSUE TITLE
Ошибка java

### ISSUE THREAD

**Issue by LilyaCharly** [Symb1OS/blackdesert-fishbot#34]
Смена удочек и поднятие лута работает корректно на домашнем ПК. Вот только первый раз появилась ошибка java. Прикрепляю скриншот и лог. 
![24](https://user-images.githubusercontent.com/39705572/50042104-f2ffe980-0067-11e9-8a0b-0a965928a26a.png)
[error.log](https://github.com/Symb1OS/blackdesert-fishbot/files/2682551/error.log)

**Comment by Symb1OS** [comment]
В это время проводились работы на сервере.
