### ISSUE TITLE
Не работает Space

### ISSUE THREAD

**Issue by shynobi13** [Symb1OS/blackdesert-fishbot#36]
Версия 1.8.2
После сегодняшнего обновления перестало работать обнаружения Space, думаю причина в том что кнопку "SPACE" перевели на русский и теперь она "ПРОБЕЛ". Прошу поправить

**Comment by OgerMW** [comment]
Не надо ничего менять, у них были ошибки с переводом, уже все вернули назад. Просто перезайдите в игру.
