### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by HottabychHaks** [Symb1OS/blackdesert-fishbot#38]
![default](https://user-images.githubusercontent.com/46067269/50373490-50acac80-05f9-11e9-8af4-3e12f4513b12.png)

**Comment by Symb1OS** [comment]
У вас установлена `JRE`.

Для работы необходимо установить [JDK](https://github.com/Symb1OS/blackdesert-fishbot/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-Java).

**Comment by HottabychHaks** [comment]
Теперь у меня не хочет прожимать клавиши что делать?

**Comment by HottabychHaks** [comment]
Я сделал так же как и в инструкции, но не работает

**Comment by Symb1OS** [comment]
Тогда нужно больше информации. 

Приложить логи, настройки бота, желательно небольшое видео, где демонстрируется настройки в игре и сама проблема

**Comment by HottabychHaks** [comment]
Вот видео

**Comment by HottabychHaks** [comment]
Чертов ютаб не дает выше 360р https://youtu.be/FNPxP3k9uQY

**Comment by HottabychHaks** [comment]
https://youtu.be/FNPxP3k9uQY

**Comment by Symb1OS** [comment]
Когда выкладываете видео, скрывайте фамилию и ник свой, забанить ведь могут.

**Comment by Symb1OS** [comment]
Складывается ощущение что вы  вообще не читали инструкцию и не смотрели видео по настройке.

[Видео по настройке и запуску](https://www.youtube.com/watch?v=CsaE7CvNHSk&t=5s).
[Так же почитайте данный раздел](https://github.com/Symb1OS/blackdesert-fishbot/wiki/%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%B1%D0%BE%D1%82%D0%B0).
