### ISSUE TITLE
Не закрывает календарь наград

### ISSUE THREAD

**Issue by OgerMW** [Symb1OS/blackdesert-fishbot#39]
Ну, собственно,название отражает суть проблемы. Из-за незакрытого календаря, не распознается капча, рыба и т.д.

**Comment by vesprin** [comment]
Сейчас по дефолту бот не закрывает календарь наград и событий перед каждым закидыванием удочки.
Чтоб всё было ок надо в файле настроек application.properties, что лежит по пути  'blackdesert-fishbot-1.8.2\target\blackdesert-fishbot_1.8.2\resources' найти строку 'bot.state.skip_calendar=false'.

И заменить значение на 'bot.state.skip_calendar=true'

Кстати, Симбиос, очень странное решение выпилить эту функцию из дефолта. По дефолту она должна быть включена. Кому надо - тот выключит. Идеально конечно было бы добавить галочку в интерфейс настроек.

**Comment by Symb1OS** [comment]
> Кстати, Симбиос, очень странное решение выпилить эту функцию из дефолта. По дефолту она должна быть включена. Кому надо - тот выключит. Идеально конечно было бы добавить галочку в интерфейс настроек.

В новой версии галочка будет вынесена в настройки.
