### ISSUE TITLE
Защиты от гм чека

### ISSUE THREAD

**Issue by UnluckyEdge** [Symb1OS/blackdesert-fishbot#4]
можно ли организовать фул выгрузку процессов при написании КЕМ ЛИБО в приватный чат \ и при перемещении по координатам ( условный суммон от гма) ?

**Comment by UnluckyEdge** [comment]
можно анализировать экран ( по градиенту)  ,   про процессы это я хз , меня чет заклинило , если тета или как там ее не воспринимает бота как бота , то пофиг, по сути при гм чеке он сможет посмотреть лог запущенный на стороне клиента   процессов  , поэтому пофиг будет ли совершена выгрузка бота из процессов в момент гм чека T_T

**Comment by UnluckyEdge** [comment]
бтв я мейби дебс немного, но где взять плату на обход защиты от эмуляции :D

**Comment by Symb1OS** [comment]
Ну самый дешевый способ - это закать с алиэкспресс, я брал там)
