### ISSUE TITLE
Не очищает капчу от шума

### ISSUE THREAD

**Issue by vesprin** [Symb1OS/blackdesert-fishbot#41]
Бот 1.8.2
ПК на Core i7 + GTX 1060, винда 7я
Режим ROBOT
- Бот не очищается капчу от шума. Очистка происходит за милисекунду, фактически по дебагу видно что капчи остаются с шумом. Иногда бывает что вводит правильно, но чаще всего фейл уже на первой букве.
Вот скрин
![noclean](https://user-images.githubusercontent.com/45634129/50550262-c22dd000-0c75-11e9-922c-9754dfcbd825.jpg)

- Как воспроизвести этот баг не знаю. 
Пробовал всё: удаление файла настроек, переустановка JDK (и 191 и 192), пересборка бота с перезагрузками.
Даже думал что дело в графике (играю на ремастере, а для бота включаю обычную), поставил стандартный пресет на высокий (чтоб не перепрыгивать на ремастер), полная переустановка всего + перезагрузка = нет результата.

resources/application.properties дефолтный, менял только кол-во удочек в интерфейсе.

Проблема появилась давно, но так и не смог решить.
Есть ли какие-то предположения? Переустановить игру и винду я могу, но может найдется более толерантный способ? :)
Заранее спасибо

**Comment by Symb1OS** [comment]
Тут сложно предполагать, так как в других состояниях скан экрана выполняется как и задуманно, а при чистке от шума возникают проблемы, хотя работает оно однотипным способом, разница лишь в том, что тут оно крутиться в цикле.

В логе с ошибками все пусто?
