### ISSUE TITLE
Прерывание работы бота

### ISSUE THREAD

**Issue by Kacka3oppo** [Symb1OS/blackdesert-fishbot#42]
- Версия приложения 1.8.2
- Производительность ПК: Высокая
- Режим работы ARDUINO
- Краткое описание: Ну тут две проблемки:
1.  
[work.log](https://github.com/Symb1OS/blackdesert-fishbot/files/2719662/work.log)
[debug.log](https://github.com/Symb1OS/blackdesert-fishbot/files/2719663/debug.log)
А именно - что значит фраза  :  Task:  auto stop complete

2.
[work.log](https://github.com/Symb1OS/blackdesert-fishbot/files/2719665/work.log)
[debug.log](https://github.com/Symb1OS/blackdesert-fishbot/files/2719666/debug.log)
Ну а тут просто:
[29.12.2018 19:10:41] - Connection manager shut down
[29.12.2018 19:10:41] - Connection manager is shutting down
[29.12.2018 19:10:41] - http-outgoing-647: Close connection
Тут бот работал в режиме робот

**Comment by Symb1OS** [comment]
1. Это означает что в настройках у вас стояла галочка с автоматическим выключением по таймеру.
![image](https://user-images.githubusercontent.com/6949746/50886691-2719c080-1402-11e9-8130-ad736417c208.png)

2. Тут точно сказать не удастся, так как неизвестно что происходило на экране в этот момент. Судя по логу он начал менять удочки по кругу, возможно появилось всплывающее окно, календарь например, либо что-то похожее.

**Comment by Kacka3oppo** [comment]
Ага, понятненько...   Отключил я все галочки.  Удалил application и после перенастроил его на формат 
[application.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/2742591/application.zip)
с тех пор уже дней 6-7 использует по 9 удочек золотых и ни одного сбоя.
Может кому пригодится....
