### ISSUE TITLE
Не собирает ивентовые ветки

### ISSUE THREAD

**Issue by haddu** [Symb1OS/blackdesert-fishbot#43]
Брал из папки unknown и кидал в ok одно изображение ветки, два, 0 - результат одинаковый, когда бот ловит палку она попадает в unknown и выбрасывается.

Вот папка [loot.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/2759011/loot.zip).

**Comment by Symb1OS** [comment]
Попробуйте немного уменьшить параметр  `bot.parsing.coefidentity=0.88`.
Думаю `0.85` должно хватить.

Файл с настройками можно найти по следующему пути -  `resources/application.properties`

**Comment by haddu** [comment]
Проблема решилась после изменения на 0.85, думаю про это стоило бы написать в FAQ.
