### ISSUE TITLE
The game is not running

### ISSUE THREAD

**Issue by m216884792** [Symb1OS/blackdesert-fishbot#45]
The game is not running
This seems to be inoperable on some servers

**Comment by Symb1OS** [comment]
What is the title of the window with the game?

**Comment by m216884792** [comment]
黑色沙漠 - xxxxx
xxxxx <--Random number

**Comment by Symb1OS** [comment]
Open file - ` blackdesert-fishbot/src/main/java/ru/namibios/arduino/Transfer.java`

Change 
`WinDef.HWND windowGame = WinAPI.findWindow("BLACK DESERT");`

to 
`WinDef.HWND windowGame = WinAPI.findWindow("黑色沙漠");`

After `build.bat` and `run.bat`

**Comment by m216884792** [comment]
![552](https://user-images.githubusercontent.com/18108943/54330173-b2f0d880-464f-11e9-91e8-f1e3d0121213.jpg)

Using Chinese brings errors

**Comment by m216884792** [comment]
[15.03.2019 11:40:55] - Bot started on FISHING mode..
[15.03.2019 11:40:55] - Bot starting over 0 second
[15.03.2019 11:40:55] - Game client crash
[15.03.2019 11:40:55] - Stop bot..
[15.03.2019 11:40:55] - Thread stop.
[15.03.2019 11:40:55] - End work.

Successfully edited
Seems to be infinitely looping

**Comment by Symb1OS** [comment]
`blackdesert-fishbot/src/main/java/ru/namibios/arduino/model/bot/State.java`

This file also needs to replace the following line `WinDef.HWND windowGame = WinAPI.findWindow("BLACK DESERT");`

**Comment by m216884792** [comment]
Maybe the difference in the picture is always waiting for the fish and won’t start fishing.
![ddf](https://user-images.githubusercontent.com/18108943/54440984-b3d05a00-4776-11e9-9faa-3db058c6ab68.jpg)

**Comment by Symb1OS** [comment]
Need add templates for your language on game.
Store templates: `Blackdesert-fishbot/resources/templates/`

Now they are not stored in a very convenient way for the user, maybe I will redo it into pictures.

**Comment by Symb1OS** [comment]
Or you can take the following screenshots and attach them here:
- space (when the character is ready to cut fish);
- status cut (BAD, GOOD, PERFECT);
- status captcha (FAILED, SUCCESS).

**Comment by m216884792** [comment]
I recommend using pictures
This makes it easier to meet the needs of other users.

**Comment by gavare** [comment]
![image](https://user-images.githubusercontent.com/8886284/54884480-b9b6f100-4e82-11e9-89ac-e46e02045258.png)
Is there something i can do to attach your bot to unofficial server?

**Comment by Symb1OS** [comment]
1) Change the title to the game. 
Open `resources/application.properties`. 
Replace game title  `bot.game_title=GAME TITLE`
2) If the language of the game is different from RU, EN, then you need to add templates. Find them here `blackdesert-fishbot/resources/templates/`

**Comment by m216884792** [comment]
How to make different templates?

**Comment by Symb1OS** [comment]
> Or you can take the following screenshots and attach them here:
> - space (when the character is ready to cut fish);
> - status cut (BAD, GOOD, PERFECT);
> - status captcha (FAILED, SUCCESS).

Attach screenshots here, and I'll add the templates myself.
