### ISSUE TITLE
Непрошенные советы и вопросы

### ISSUE THREAD

**Issue by TrurlMcByte** [Symb1OS/blackdesert-fishbot#46]
1. А почему парсится вся капча целиком, если она состоит из набора фиксированных частей? Если их парсить по отдельности, то объем распознавания будет на порядки меньше. И от длины зависеть будет меньше.
2. Из клиента легко вытаскиваются все картинки рыб и легко получить их редкость (надо?). Кроме того можно было бы просто по цвету рамки узнавать ценность лута, но это не спортивно.
3. А почему только 3 ячейки проверяется? На эвентах до 8 ячеек за поклёвку доходит иногда. А у меня сегодня было по 4 куска дискотеки сразу аж 2 раза почти подряд (в Пустом море).

**Comment by Symb1OS** [comment]
> А почему парсится вся капча целиком, если она состоит из набора фиксированных частей? Если их парсить по отдельности, то объем распознавания будет на порядки меньше. И от длины зависеть будет меньше.

Потому что это лишняя работа, которая не дает никаких преимуществ. Нету смысла разбивать ее на части, потому как я все равно скармливаю ее нейронке. Ну и вслучае добавления поддержки других разрешений данное решение легко расширяется. 

> Из клиента легко вытаскиваются все картинки рыб и легко получить их редкость (надо?). Кроме того можно было бы просто по цвету рамки узнавать ценность лута, но это не спортивно.

Ну если они у вас есть в удобном виде и отсортированные, тогда не откажусь. Я их просто переформатирую в необходимый боту вид. 

> А почему только 3 ячейки проверяется? На эвентах до 8 ячеек за поклёвку доходит иногда. А у меня сегодня было по 4 куска дискотеки сразу аж 2 раза почти подряд (в Пустом море).

Потому что больше 3 мне не встречалось, но я в море бота особо не использовал. Могу без проблем добавить хоть 9, желательно кинуть побольше скринов с количеством лута > 3, чтобы я мог на них потестить.

**Comment by TrurlMcByte** [comment]
> Потому что это лишняя работа, которая не дает никаких преимуществ. Нету смысла разбивать ее на части, потому как я все равно скармливаю ее нейронке.
Я не так много работал с нейронками, но то что одна сложная задача решается труднее, чем она же, разбитая на насколько простых однотипных - это совершенно точно, причем разница на порядки. Та же длина капчи в этом случае не будет иметь никакого значения для самого распознавания.

Насчет удобности картинок из клиента не скажу, я с графикой мало работаю, тут голые dds без фона : https://goharu.ams3.cdn.digitaloceanspaces.com/tmp/out_dds.zip

**Comment by Symb1OS** [comment]
> Та же длина капчи в этом случае не будет иметь никакого значения для самого распознавания.

Да, изначально неправильно понял первый пункт. Это верно, в таком случае и длина капчи не имела бы значение, да и сама нейронка получилась бы намного проще с гораздно более меньшим количеством слоев. Просто так надо было делать изначально, а переписывать сейчас то, что и так работает как-то сомнительно, сейчас намного проще доучить в случае чего. Уже не припомню почему изначально начал делать именно так.

**Comment by TrurlMcByte** [comment]
Спасибо, так и подумал что это "исторически сложилось" 👍
