### ISSUE TITLE
Не начинает рыбалку

### ISSUE THREAD

**Issue by Quaterberg** [Symb1OS/blackdesert-fishbot#48]
Бот не кидает удочку, лог прикладываю, как и application.properties. Режим работы - ROBOT.

[вложения.ZIP](https://github.com/Symb1OS/blackdesert-fishbot/files/3055467/default.ZIP)

**Comment by Symb1OS** [comment]
> Бот не прожимает клавиши
>- Проверить в активном ли режиме находися окно с игрой.
> - Бот должен быть запущен от имени администратора. Для этого необходимо нажать правой кнопкой мыши по run.bat, запустить от имени администратора.

**Comment by Quaterberg** [comment]
Увы. Вот сделал запись с экрана
https://www.youtube.com/watch?v=1z5qsGJZPJw
Батник конечно же запускаю от имени администратора
