### ISSUE TITLE
не считывает капчу

### ISSUE THREAD

**Issue by Hronyx** [Symb1OS/blackdesert-fishbot#51]
### 

> **_Прежде_** чем отправлять информацию о проблеме:

- [ ] Удостоверьтесь, что пользуетесь последней версией.
- [ ] Поищите упоминание об этом баге, возможно, отчёт о нём уже был раньше.
- [ ] Если вам дали решение на вашу проблему и у вас возникла новая, просьба создавать новую задачу, не нужно все писать в одну тему, чтобы облегчить поиски другим пользователям, которые столкнулись с той же проблемой.

Отчёты о багах должны содержать:
- Версию приложения.
- Сервер (`RU/EU/Пиратка`)
- Тип ПК (`Стационар/Ноутбук`).
- Производительность ПК (`Низкая/Средняя/Высокая`).
- Режим работы (`ROBOT`/`ARDUINO`).
- Краткое описание.
- Как вы столкнулись с багом? Инструкция по воспроизведению.
- Содержимое папки `logs`.
- Содержимое `resources/application.properties`.
- По мере возможности, прикрепите визуальное подтверждение бага. Скриншоты, видео и/или анимационные гифы.

Задачи, которые не содержат в себе никакой информации для анализа игнорируются.

**Comment by Hronyx** [comment]
как мне добавить лог ошибки сюда?

**Comment by Symb1OS** [comment]
@Hronyx 
А в чем сложность? Перетащить файлики с логами сюда и подробно описать условия при которых возникает проблема . При возможности можно снять коротенькое видео, где демострируется проблема.

**Comment by Hronyx** [comment]
попытался переустановить, теперь вовсе не получается даже установить. открываю exe файл меня  отправляют на какой-то сайт и дальше ничего не происходит... что делать даже не знаю

**Comment by Symb1OS** [comment]
Пишите конкретно по пунктам что делаете и что не получается,  не будет деталей, я не смогу вам помочь.
Скрины/видео желательны.

**Comment by Hronyx** [comment]
Прошу простить меня, за беспокойство, проблему решил подбором задержек, на данный момент бот работает как положено
