### ISSUE TITLE
Работа бота

### ISSUE THREAD

**Issue by MastaDan9** [Symb1OS/blackdesert-fishbot#54]
Добрый день. Бот еще работает ?

**Comment by MastaDan9** [comment]
Удочку забрасывает сам, но когда клев пошел не нажимает SPACE

**Comment by Symb1OS** [comment]
@MastaDan9 
Необходимо зайти  в `Настройки > Отладка`, выставить галочку `Ожидание рыбы`.
Запустить бота и дать немного поработать, после чего  заахивировать  папку `debug/waitfish` и выложить ее сюда вместе с логами.

**Comment by MastaDan9** [comment]
[waitfish.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/3535610/waitfish.zip)
[logs.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/3535615/logs.zip)
Чет как я понял он не те координаты считывает?)

**Comment by Symb1OS** [comment]
> Чет как я понял он не те координаты считывает?)

Может после обновления что-то изменили.
Просьба снять небольшое видео, чтобы я смог обновить координаты.

**Comment by MastaDan9** [comment]
https://dropmefiles.com/aLQoV

**Comment by MastaDan9** [comment]
Помогло?

**Comment by Symb1OS** [comment]
Видео необходимо в Full HD.

Вообще скорее что-то с настройками, так как если бы были изменения в игре у других бот так же перестал работать.

**Comment by MastaDan9** [comment]
Пробовал на ноутбуке, так же не нажимал кнопку space. Может скринами лучше ?)

**Comment by Symb1OS** [comment]
Можно и скрин, чтобы было видно желтую кнопку Space.

**Comment by MastaDan9** [comment]
![Screenshot_28](https://user-images.githubusercontent.com/7467926/63687942-a7185d80-c80e-11e9-8e54-a8ea652f513f.png)
1920-1080

**Comment by MastaDan9** [comment]
Жаль что разрешение только фулл хд) играю в 2560х1080. Было б круто иметь возможно самому менять настройки координат)

**Comment by MastaDan9** [comment]
В игре был добавлен фильтр лута, походу из-за этого съехала кнопка Space

**Comment by MastaDan9** [comment]
поменял координаты Space, все заработало

**Comment by Symb1OS** [comment]
Напишите на какие сменили, будет время - обновлю бота.

**Comment by MastaDan9** [comment]
928x286 у Space
