### ISSUE TITLE
оплатил премиум на 50 рублей ночью с карты и все ключ до сих пор не активен

### ISSUE THREAD

**Issue by kisey91** [Symb1OS/blackdesert-fishbot#55]
Прежде чем отправлять информацию о проблеме:
- [x] Удостоверьтесь, что пользуетесь последней версией.
- [x] Поищите упоминание об этом баге, возможно, отчёт о нём уже был раньше.
- [x] Если вам дали решение на вашу проблему и у вас возникла новая, просьба создавать новую задачу, не нужно все писать в одну тему, чтобы облегчить поиски другим пользователям, которые столкнулись с той же проблемой.

Отчёты о багах должны содержать:
- Версию приложения.
- Сервер (`RU/EU/Пиратка`)
- Тип ПК (`Стационар/Ноутбук`).
- Производительность ПК (`Низкая/Средняя/Высокая`).
- Режим работы (`ROBOT`/`ARDUINO`).
- Краткое описание.
- Как вы столкнулись с багом? Инструкция по воспроизведению.
- Содержимое папки `logs`.
- Содержимое `resources/application.properties`.
- По мере возможности, прикрепите визуальное подтверждение бага. Скриншоты, видео и/или анимационные гифы.

Задачи, которые не содержат в себе никакой информации для анализа игнорируются.

**Comment by Symb1OS** [comment]
Ответил на почту
