### ISSUE TITLE
Эмуляция в окне

### ISSUE THREAD

**Issue by MastaDan9** [Symb1OS/blackdesert-fishbot#56]
Добрый день. 
Интересно, реально ли сделать разгадывание и эмуляцию в неактивном окне? Например на втором мониторе открыта игра с софтом, а на первом мониторе работать и не мешать софту)

**Comment by Symb1OS** [comment]
Добрый день.

Нет, при текущий реализации так сделать не получится. В таком варианте как сейчас бот более безопасный, так как никак не вмешивается в процессы игры.
