### ISSUE TITLE
Please Again with Java.io error

### ISSUE THREAD

**Issue by exodia0x** [Symb1OS/blackdesert-fishbot#59]
![ภาพ](https://user-images.githubusercontent.com/38641615/65374997-723ae180-dcba-11e9-9212-8fdee0abe11d.png)

**Comment by MastaDan9** [comment]
Такая же ошибка, чистая система win 10 64
Java 8 по ссылке поставил, в чем может быть проблема ?

**Comment by Symb1OS** [comment]
Проверьте сейчас

**Comment by MastaDan9** [comment]
Спасибо, все работает теперь. 
Но кстати есть вопрос, сколько пользуюсь ботов, все время он останавливается на "Check status parsing captcha" - Status not identified. На этом этапе слегка подтупливает. 
В целом работает отлично)

**Comment by Symb1OS** [comment]
Когда в следующий раз возникнет подобное, просьба создать новую задачу и приложить туда логи.
