### ISSUE TITLE
Изменение окна трофеи

### ISSUE THREAD

**Issue by MastaDan9** [Symb1OS/blackdesert-fishbot#60]
Добрый день.
Два дня назад было обновление на РУ серверах, там слегка поменяли интерфейс. Теперь ячеек 12 и они я так понял смещены, по логу бот, изменились координаты ячеек. Подскажи, в настройках бота первая координата "Слот 1" 1560х618, это какое место ячейки, центр, углы лево право?
http://prntscr.com/phcdc3

**Comment by Symb1OS** [comment]
Добрый.

Порядок ячеек сверху вниз слева направо.

Там две настройки отвечающие за окно с трофеями.
1)  Отвечает за ячейку лута, которая сканируется в формате (x,y, длина, ширина).
`bot.screen.loot_slot_list=1539,597,43,43; 1586,597,43,43; 1633,597,43,43; 1680,597,43,43; 1539,644,43,43; 1586,644,43,43; 1633,644,43,43; 1680,644,43,43`
2) Координата середины ячейки, куда нажмет бот чтобы полнять лут.
`bot.loot.touch={1560,618};{1607,618};{1654,618};{1701,618};{1560,665};{1607,665};{1654,665};{1701,665}`

Просьба скинуть целый скрин на котором видно новое окно с трофеями, желательно несколько штук, исправлю.

**Comment by MastaDan9** [comment]
![2019-10-10_-1983373100](https://user-images.githubusercontent.com/7467926/66562269-f1a62d00-eb63-11e9-8f53-9fba2195913f.png)
![2019-10-10_-1983164454](https://user-images.githubusercontent.com/7467926/66562531-87da5300-eb64-11e9-8060-1f36c3956b82.png)
![2019-10-10_-1983194221](https://user-images.githubusercontent.com/7467926/66562533-87da5300-eb64-11e9-9439-32fc779b826c.png)
Сделал

**Comment by Symb1OS** [comment]
По возможности просьба приложить скрины, где ячеек лута больше 1.

**Comment by MastaDan9** [comment]
![2019-10-10_-1970191939](https://user-images.githubusercontent.com/7467926/66577764-98012b00-eb82-11e9-883c-e65052aeb35d.png)

**Comment by Symb1OS** [comment]
Просьба протестировать [blackdesert-fishbot_1.9.0.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/3713366/blackdesert-fishbot_1.9.0.zip).

Перед использоваем необходимо удалить `C:\Users\$USER\fishbotkey`. Если на ключе есть премиум, тогда необходимо сохранить резервную копию файла.

Так же пришлось удалить все старые шаблоны лута из `resources/loot`, так что коллекцию придется собирать заново. За исключением `empty/empty.jpg`, `fish/1.jpg`, `fish/2.jpg`. В остальных файлах лежат заглушки, так как бот не запустится если в папке не будет хотя бы одного файлика.

После теста просьба приложить основные иконки типо (камней реликвий, ключи,  золотая рыба, все что получится собрать из полезного).

**Comment by MastaDan9** [comment]
http://prntscr.com/phmvg8
[error.log](https://github.com/Symb1OS/blackdesert-fishbot/files/3714552/error.log)
[work.log](https://github.com/Symb1OS/blackdesert-fishbot/files/3714554/work.log)

**Comment by Symb1OS** [comment]
Исправил, просьба проверить.

**Comment by MastaDan9** [comment]
вроде все нормально, правда капча в последнюю секунду разгадывается, в независимости сколько там букв 2 или 7, но вроде успевает) позже скину архив рыб

**Comment by MastaDan9** [comment]
![image](https://user-images.githubusercontent.com/7467926/66647590-ff29e880-ec31-11e9-8675-ac99257b0f48.png)
не успел мощный клев)

**Comment by Symb1OS** [comment]
Со временем должен немного разогнаться

**Comment by MastaDan9** [comment]
изменил задержку с 150 до 130, стал хотя б капчи большие успевать, а то часто не успевал

**Comment by MastaDan9** [comment]
Второй слот не подбирает, в первом слоте был треш, во втором осколок. 
![image](https://user-images.githubusercontent.com/7467926/66698843-42e02900-ecea-11e9-850d-addefc206363.png)

**Comment by MastaDan9** [comment]
так же проблема осталась с разгадыванием, он не успевает капчи разгадывать, из 10 раз может половину не разгадать, до этой обновы такого не было)

**Comment by MastaDan9** [comment]
> Второй слот не подбирает, в первом слоте был треш, во втором осколок.
> ![image](https://user-images.githubusercontent.com/7467926/66698843-42e02900-ecea-11e9-850d-addefc206363.png)

Проверил много раз, второй слот не подбирает(

**Comment by Symb1OS** [comment]
В следующий раз просьба сделать скрин на котором видно окно с лутом в 2 слота, а так же приложить папку с шаблонами лута.

**Comment by Symb1OS** [comment]
[blackdesert-fishbot_1.9.0.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/3723724/blackdesert-fishbot_1.9.0.zip)

Данная сборка будет самостоятельно делать скрины на этапе фильтра лута и сохранять их в `resources/debug`.

Как соберется достаточное количество просьба приложить сюда. Так же если опять обнаружите что не подбирает какой-либо слот необходимо зафиксировать время. Так же необходимо приложить шаблоны лута `resources/loot`.

**Comment by Symb1OS** [comment]
Тут скорее всего дело в том, что в качестве второго слота вам выпадал ивент-сундук.

Чтобы он распознавался можно немного уменьшить "коэффициент узнаваемости", за это отвечает параметр `bot.parsing.coefidentity`,  0.82 должно хватить.

Так же доступна новая версия - [1.9.0](https://github.com/Symb1OS/blackdesert-fishbot/releases/tag/1.9.0)

**Comment by MastaDan9** [comment]
во втором слоте был кусок)

**Comment by MastaDan9** [comment]
![image](https://user-images.githubusercontent.com/7467926/66920333-b99f5e00-f02b-11e9-9c8d-541ac8039329.png)

**Comment by Symb1OS** [comment]
Новую версию скачайте

**Comment by Symb1OS** [comment]
Выполните в консоли:
`java -version`

И покажите вывод.

**Comment by MastaDan9** [comment]
![image](https://user-images.githubusercontent.com/7467926/66936327-2cb5ce00-f046-11e9-9cff-0e95e88ffd8a.png)

**Comment by Symb1OS** [comment]
Значит не заменили PATH, в выводе должна быть java 13

**Comment by MastaDan9** [comment]
как оказалось нужно было удалить строчку из PATH "C:\Program Files (x86)\Common Files\Oracle\Java\javapath;" 
Она запускала старую версию. Статья по этой проблеме (может кто-то еще столкнется) https://ubuntugeeks.com/questions/394081/how-to-change-java-version-on-windows-10
