### ISSUE TITLE
при включении бот сам закрывается

### ISSUE THREAD

**Issue by Hronyx** [Symb1OS/blackdesert-fishbot#62]
[debug.log](https://github.com/Symb1OS/blackdesert-fishbot/files/3932856/debug.log)
[error.log](https://github.com/Symb1OS/blackdesert-fishbot/files/3932857/error.log)
[work.log](https://github.com/Symb1OS/blackdesert-fishbot/files/3932858/work.log)

Прежде чем отправлять информацию о проблеме:
- [x] Удостоверьтесь, что пользуетесь последней версией.
- [x] Поищите упоминание об этом баге, возможно, отчёт о нём уже был раньше.
- [ ] Если вам дали решение на вашу проблему и у вас возникла новая, просьба создавать новую задачу, не нужно все писать в одну тему, чтобы облегчить поиски другим пользователям, которые столкнулись с той же проблемой.

Отчёты о багах должны содержать:
- Версию приложения.
- Сервер (`RU/EU/Пиратка`)
- Тип ПК (`Стационар/Ноутбук`).
- Производительность ПК (`Низкая/Средняя/Высокая`).
- Режим работы (`ROBOT`/`ARDUINO`).
- Краткое описание.
- Как вы столкнулись с багом? Инструкция по воспроизведению.
- Содержимое папки `logs`.
- Содержимое `resources/application.properties`.
- По мере возможности, прикрепите визуальное подтверждение бага. Скриншоты, видео и/или анимационные гифы.

Задачи, которые не содержат в себе никакой информации для анализа игнорируются.

**Comment by Hronyx** [comment]
играю на пиратке GamezBD

**Comment by Hronyx** [comment]
Как я понимаю бот не видит запущенную игру

**Comment by Symb1OS** [comment]
Вам необходимо узнать наименование окна с игрой, после чего открыть файл с настройками `resources/application.properties`

Найти и заменить свойство - `bot.game_title`

**Comment by Hronyx** [comment]
а вы не подскажете мне как найти имя окна с игрой

**Comment by Symb1OS** [comment]
Запустить игру в оконном режиме, во рамке окна будет название

**Comment by Hronyx** [comment]
все получилось. вот только бот не нажимает клавиши

**Comment by Symb1OS** [comment]
Бот от имени администратора запущен?

**Comment by Hronyx** [comment]
да, запускаю от админа и все равно клавиши он не нажимает
