### ISSUE TITLE
Не могу установить бота

### ISSUE THREAD

**Issue by Sweefee** [Symb1OS/blackdesert-fishbot#64]
Скачал последнюю версию бота blackdesert-fishbot_2.0.0
Делаю всё по гайду на ютубе, при запуске файла test.bat в конце всех операций вылезает ошибка. Как исправить?
[INFO] Reactor Summary:
[INFO]
[INFO] blackdesert-fishbot 2.0.0 .......................... SUCCESS [  0.017 s]
[INFO] bdofishbot-base .................................... SUCCESS [  3.355 s]
[INFO] bdofishbot-utils ................................... SUCCESS [  0.455 s]
[INFO] bdofishbot-bot ..................................... FAILURE [ 28.442 s]
[INFO] bdofishbot-gui ..................................... SKIPPED
[INFO] bdofishbot 2.0.0 ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.997 s
[INFO] Finished at: 2020-01-12T13:11:10+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project bdofishbot-bot: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Default user.COMPUTER\Desktop\blackdesert-fishbot_2.0.0\bdofishbot-bot\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :bdofishbot-bot

**Comment by Symb1OS** [comment]
После обновления визуала рыбалки бот временно не работает. Требуется доработка.
