### ISSUE TITLE
build succesfull but test not connection refused

### ISSUE THREAD

**Issue by latrailer** [Symb1OS/blackdesert-fishbot#65]
test.bat: http://prntscr.com/qqga3g
test.bat TEST RESULT : http://prntscr.com/qqgdyh
failed connect to nambios.ru connection refused
build.bat :http://prntscr.com/qqgb5a

**Comment by ZeLixShow** [comment]
Same problem

**Comment by ZeLixShow** [comment]
[ru.namibios.bdofishbot.bot.HttpServiceTest.txt](https://github.com/Symb1OS/blackdesert-fishbot/files/4469652/ru.namibios.bdofishbot.bot.HttpServiceTest.txt)

**Comment by diegobh** [comment]
any fix, please?

**Comment by zoe08** [comment]
download the latest version: https://github.com/Symb1OS/blackdesert-fishbot/releases
Then set JAVA_HOME:
Do one of the following:
Windows 7 – Right click My Computer and select Properties > Advanced
Windows 8 – Go to Control Panel > System > Advanced System Settings
Windows 10 – Search for Environment Variables then select Edit the system environment variables
Click the Environment Variables button.
Under System Variables, click New.
In the Variable Name field, enter either:
JAVA_HOME if you installed the JDK (Java Development Kit)
For PATH, edit the one you have and add: C:\Program Files\Java\jdk-13.0.2\bin.

Then open a CMD and execute run.bat
It should open the bot

**Comment by Symb1OS** [comment]
The bot's server is down, so the test fails.

The bot needs to be finished for the current version of the game, in the near future there will hardly be a fix, there is no desire to do this at the moment.
