### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by MastaDan9** [Symb1OS/blackdesert-fishbot#66]
Привет. Будут ли обновления? Там интерфейс завезли новый на РУ. Стало чуть проще, убрали шум с букв и тд. Просто надо переделать ) Был бы благодарен за обнову

**Comment by Symb1OS** [comment]
Добрый день,

Если есть желание помочь, то необходимо записать видео:
- разрешение в игре и в видео 1920х1080;
- настройки в игре должны быть такими же, как когда используете бота (минимальная
    яркость, максимальная контрастность);
- в видео должны попасть все статусы рыбалки:
  - неудачная\хорошая\отличная подсечка;
  - удачный\неудачный ввод капчи;
  - окно с лутом.

Таким образом у меня будет материал с которым работать.
