### ISSUE TITLE
Wait fish... Don't detects the fishs

### ISSUE THREAD

**Issue by diegobh** [Symb1OS/blackdesert-fishbot#67]
i changed the ApplicationConfig.java the bot game title to match wth my game.

but it stays on Waiting fish...

The fish bait but isn't detected by the bot.

i'm playing at 1920x1080 full screen window.
I didn't changed no other config.

Any idea how fix it, please?

ty very much!!!

**Comment by Symb1OS** [comment]
Bot not work for current version game. Need to finalize, but no time yet

**Comment by diegobh** [comment]
> Bot not work for current version game. Need to finalize, but no time yet

omg. Sorry, i have no idea how to help you. 

btw thank you very much ;)
