### ISSUE TITLE
извини что за ошибка и как исправить?

### ISSUE THREAD

**Issue by narkuala** [Symb1OS/blackdesert-fishbot#68]
Failed tests:   parseByteCaptchaByName(ru.namibios.bdofishbot.bot.HttpServiceTest): expected:<[wdwda]> but was:<[]>

Tests run: 64, Failures: 1, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] blackdesert-fishbot 2.0.0 .......................... SUCCESS [  0.018 s]
[INFO] bdofishbot-base .................................... SUCCESS [  2.919 s]
[INFO] bdofishbot-utils ................................... SUCCESS [  0.436 s]
[INFO] bdofishbot-bot ..................................... FAILURE [ 49.636 s]
[INFO] bdofishbot-gui ..................................... SKIPPED
[INFO] bdofishbot 2.0.0 ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.447 s
[INFO] Finished at: 2020-08-19T01:16:40+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project bdofishbot-bot: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\narku\Desktop\blackdesert-fishbot-master\bdofishbot-bot\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :bdofishbot-bot

**Comment by Symb1OS** [comment]
Сервер для работы бота отключен, поэтому тест не проходит.

Бот нужно допиливать под текущую версию игры, в ближайшее время вряд ли будет исправление, нет желания этим заниматься на данный момент.
