### ISSUE TITLE
Новости/News

### ISSUE THREAD

**Issue by Symb1OS** [Symb1OS/blackdesert-fishbot#69]
На данный момент бот не поддерживается, нет мотивации им больше заниматься.
***
At the moment, the bot is not supported, there is no motivation to do it anymore.

**Comment by muratulashozturk** [comment]
Why????

**Comment by MastaDan9** [comment]
Жаль, только скринов наделал )

**Comment by Symb1OS** [comment]
Бот обновлен.

[Новая версия](https://github.com/Symb1OS/blackdesert-fishbot/releases/latest)
