### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by MastaDan9** [Symb1OS/blackdesert-fishbot#7]
Привет. 
Для работы бота нужно купить только Arduino Pro Micro и просто подключить его к USB порту, далее все софтом настраивается, правильно я понимаю ?

**Comment by Symb1OS** [comment]
Привет.

Плата ардуино больше НЕ обязательна, бот может работать как с ней, так и без нее (просто пропускам установку Arduino IDE и заливку скетча на плату).

Для работы без платы в настройках необходимо выбрать пункт `ROBOT`.

**Comment by MastaDan9** [comment]
А есть ли разница работы с платой и без? В плане безопасности и т.д.? 

У меня имеется такая плата, думаю попробовать с ней)

**Comment by Symb1OS** [comment]
Ардуино на данный момент поддерживает чуть меньше функций.

Например пока невозможно настроить повтор работ для рабочих после использования пива.
А так же анализируется только 2 слота после удачной рыбалки. 

В остальном различий нет.

**Comment by MastaDan9** [comment]
Почему-то перестал нажимать Space, когда рыбу надо подсекать уже.
Работает через arduino. Уже и переустановил всё заново, не помогло. Все настройки идентичны как и в WiKi, яркость на минимуме. 

Либо бывает такое что нажмет Space но на проверке лута останавливается и всё.

**Comment by Symb1OS** [comment]
А после каких действий перестал подсекать?

Просьба выгрузить свои настройки их игры и тут приложить, мне не удается воспроизвести проблему.

**Comment by MastaDan9** [comment]
Странно, но работал, а потом просто перестал работать. 
Методом тыка я вроде бы определил что в полноэкранном режиме без рамок, он не может нажать на Space когда нужно подсекать, если перейти в экранный режим и чуть сдвинуть вниз то нажимает на пробел, но после этого все равно не может нажать Spacе и разгадать капчу.

Настройки игры:
http://skrinshoter.ru/s/271118/bGc0tFbN
http://skrinshoter.ru/s/271118/nhLEH8aL

Настройки бота:
http://skrinshoter.ru/s/271118/zYlWrt10


По порядку:
В игре выставляю настройки как на скрине
Запускаю run.bat от админа
Нажимаю старт и переключаюсь на игру
Бот начинает работать, скипает календарь и забрасывает удочку.
После этого очень долго Wait fish, даже если она клюет.
После длительного ожидания, бот открывает инвентарь и меняет удочку и еще раз забрасывает и так по кругу

[debug.log](https://github.com/Symb1OS/blackdesert-fishbot/files/2619239/debug.log)

**Comment by MastaDan9** [comment]
Залил небольшое видео. https://youtu.be/9JK-Cb9gtfY

**Comment by Symb1OS** [comment]
У вас что-то с настройками интерфейса, кнопка "Нажмите Space" находится выше, чем должна быть.

Попробуйте открыть `resources/application.properties`, найти и заменить следующий значения: 
```
bot.screen.space=928, 190, 63, 25
bot.screen.space.offset.y=40
bot.screen.space.offset.x=0
```

После этого он по идее начнет подсекать рыбу, но возможно что перестанет выполнять все остальное, потому как стандартные значения у вас по какой-то причине смещены.

По результатам просьба отписать, помогло ли.

**Comment by MastaDan9** [comment]
В версии бота blackdesert-fishbot-1.7.5 нет файла `resources/application.properties`
Скачал обновленную версию 1.7.6, заменил в этом файле. 
В режиме `ROBOT` все работает отлично.
В режиме Arduino, после запуска бот сразу закрывается, в настройках COM выбран....
В логах выдает ошибку `Port is closed. Check your port in settings or change the mode work` Как это понимать ?)

**Comment by MastaDan9** [comment]
Все работает теперь, кроме смены удочек) Не меняет, не открывает инвентарь. 
Все удочки в первой строке.

**Comment by Symb1OS** [comment]
[Нужно больше информации](https://github.com/Symb1OS/blackdesert-fishbot/blob/master/ISSUE_TEMPLATE.md)

**Comment by Symb1OS** [comment]
Темы закрываю. 

В случае возникновения новых проблем необходимо создавать отдельную задачу, чтобы облегчить поиски другим пользователям, которые столкнулись с подобной проблемой.
