### ISSUE TITLE
Error test

### ISSUE THREAD

**Issue by Svituk** [Symb1OS/blackdesert-fishbot#70]
[INFO] Reactor Summary:
[INFO]
[INFO] blackdesert-fishbot 2.0.0 .......................... SUCCESS [  0.009 s]
[INFO] bdofishbot-base .................................... SUCCESS [  1.034 s]
[INFO] bdofishbot-utils ................................... SUCCESS [  0.167 s]
[INFO] bdofishbot-bot ..................................... FAILURE [ 45.561 s]
[INFO] bdofishbot-gui ..................................... SKIPPED
[INFO] bdofishbot 2.0.0 ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.944 s
[INFO] Finished at: 2020-10-11T18:59:59+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project bdofishbot-bot: There are test failures.
[ERROR]
[ERROR] Please refer to D:\bot\blackdesert-fishbot-2.0.0\bdofishbot-bot\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :bdofishbot-bot
Для продолжения нажмите любую клавишу . . .

**Comment by Symb1OS** [comment]
Добрый день

Сервер для работы бота отключен, поэтому тест не проходит.

Боту для работы требуется доработка, но в ближайшее время я врядли буду делать его вновь работоспособным.

**Comment by Symb1OS** [comment]
Бот обновлен.

[Новая версия](https://github.com/Symb1OS/blackdesert-fishbot/releases/latest)
