### ISSUE TITLE
Проблемы с нажатием

### ISSUE THREAD

**Issue by SBleak** [Symb1OS/blackdesert-fishbot#8]
Бот всё прекрасно понимает на экране, видит что нужно подсекать и прочее, выдавая сообщение в окошке, что он жмёт пробел и прочее, обнаружена рыба и тд. Но не забрасывает удочку и вообще не жмёт клавиши. Думал надо поставить эмулятор, что в комплекте, выбрал плату, но вкладка порт неактивна. То ли я дурак, то ли у меня какая-то особенная ситуация. Можете помочь?

**Comment by Symb1OS** [comment]
Это означает то что бот запущен без прав администратора.

Необходимо:
> Правой кнопкой мыши по run.bat. Запустить от имени администратора.

**Comment by SBleak** [comment]
> Это означает то что бот запущен без прав администратора.
> 
> Необходимо:
> 
> > Правой кнопкой мыши по run.bat. Запустить от имени администратора.

Вы были правы. Если это цитата, то я невнимательно прочитал остальные ветки. А где лучше рыбачить с ботом? Мне была бы полезна информация. Просто как рыбачить в море я темы и гайды видел, разве так и с ботов рыбачат?

**Comment by SBleak** [comment]
Кстати бот классный!

**Comment by Symb1OS** [comment]
> > Это означает то что бот запущен без прав администратора.
> > Необходимо:
> > > Правой кнопкой мыши по run.bat. Запустить от имени администратора.
> 
> Вы были правы. Если это цитата, то я невнимательно прочитал остальные ветки. А где лучше рыбачить с ботом? Мне была бы полезна информация. Просто как рыбачить в море я темы и гайды видел, разве так и с ботов рыбачат?

По поводу хороших мест не подскажу, я использовал бот исключительно для ловли кусков дискотек)

**Comment by SBleak** [comment]
> > > Это означает то что бот запущен без прав администратора.
> > > Необходимо:
> > > > Правой кнопкой мыши по run.bat. Запустить от имени администратора.
> > 
> > 
> > Вы были правы. Если это цитата, то я невнимательно прочитал остальные ветки. А где лучше рыбачить с ботом? Мне была бы полезна информация. Просто как рыбачить в море я темы и гайды видел, разве так и с ботов рыбачат?
> 
> По поводу хороших мест не подскажу, я использовал бот исключительно для ловли кусков дискотек)

Бот долго проверяет статус ввода капчи так и должно быть?

**Comment by Symb1OS** [comment]
Такое может возникать при парсинге первой капчи, он впервый раз долго соображает, во все последующие проблем возникать не должно)

**Comment by SBleak** [comment]
> Такое может возникать при парсинге первой капчи, он впервый раз долго соображает, во все последующие проблем возникать не должно)

Вы планируете добавлять ,например, аукцион бота?

**Comment by Symb1OS** [comment]
> Вы планируете добавлять ,например, аукцион бота?

В ближайшее время не планировал, но в дальнейшем возможно добавлю, если необходимость будет)

**Comment by Symb1OS** [comment]
Какую версию бота вы используете, `1.7.5` ?

Попробуйте использовать [новую версию](https://github.com/Symb1OS/blackdesert-fishbot/releases/latest).

**Comment by Symb1OS** [comment]
Темы закрываю.

В случае возникновения новых проблем необходимо создавать отдельную задачу, чтобы облегчить поиски другим пользователям, которые столкнулись с подобной проблемой.
