### ISSUE TITLE
факапиться на яве 

### ISSUE THREAD

**Issue by darkrage1488** [Symb1OS/blackdesert-fishbot#9]
http://skrinshoter.ru/s/281118/8NwriazK?a

**Comment by Symb1OS** [comment]
У вас установлена `JRE`.

Необходимо установить `JDK`. Инструкция [тут](https://github.com/Symb1OS/blackdesert-fishbot/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-Java)
